### ISSUE TITLE
Has been removed from store?

### ISSUE THREAD

**Issue by robindijkhof** [beizhedenglong/chrome-qrcode-reader#10]
Link seems to be dead. Also, I cant find it in the store.

**Comment by beizhedenglong** [comment]
I haven't maintained this for a long time. I checked the email and found an email from google saying
> Description provided is insufficient to understand the functionality of the item.

It's has been taken down.  I changed the description and submitted to google for review

**Comment by beizhedenglong** [comment]
It's available in the store now.
